/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:0e672b2f-cd28-4d12-bb7c-96010c36bd8e",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_g0H2lixtG",
    "aws_user_pools_web_client_id": "19v0he0k3nu2u3mjsule0u6jl8",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3xvgr4gdqjcxdmwfj52jnqrfii.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qojqgsmdejaj5p3xlw4ckeiwhm",
    "aws_user_files_s3_bucket": "nakaosimagedb132115-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
