/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:0e672b2f-cd28-4d12-bb7c-96010c36bd8e",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_g0H2lixtG",
    "aws_user_pools_web_client_id": "19v0he0k3nu2u3mjsule0u6jl8",
    "oauth": {}
};


export default awsmobile;
